# https://taskfile.dev
version: '3'

dotenv: ['.env']
silent: false

includes:
  terraform: .task/terraform.yml
  ansible: .task/ansible.yml

tasks:
  init:
    desc: Init infrastructure to Yandex Cloud
    summary: |
      Initialize project

      Create infrastructure for the project.
    cmds:
      - task: terraform:apply

  deploy:
    desc: Deploy project
    summary: |
      Deploy project

      Deploy your clickhouse project in the selected environment.
      Please make sure that you run `task init` first.
    cmds:
      - task: ansible:galaxy
      - task: ansible:playbook

  destroy:
    desc: Destroy project
    summary: |
      Destroy project

      Destroy your clickhouse project.
    cmds:
      - task: terraform:destroy

 